on:
  pull_request:
    branches:
      - main

name: Validate PR

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@master
        with:
          go-version: 1.15
      - name: Checkout code
        uses: actions/checkout@v2
      - run: go get github.com/mitchellh/gox
      - run: gox -osarch="darwin/amd64 darwin/arm64 linux/386 linux/amd64 linux/arm" -output="build/bedrock-{{.OS}}-{{.Arch}}"
