on:
  pull_request:
    branches:
      - main

name: Validate PR

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Build
        run: |
          go get github.com/mitchellh/gox@latest
          gox -osarch="darwin/amd64 darwin/arm64 linux/386 linux/amd64 linux/arm" -output="build/bedrock-{{.OS}}-{{.Arch}}"
