on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Build
        run: |
          go install github.com/mitchellh/gox@latest
          gox -osarch="darwin/amd64 darwin/arm64 linux/386 linux/amd64 linux/arm" -output="build/bedrock-{{.OS}}-{{.Arch}}"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*
